import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/components/providers'

export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className="">
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
